### ISSUE TITLE
compressor recipe repeat

### ISSUE THREAD

**Issue by JackMeds** [GregTechCEu/gregicality-skyblock-edition#10]
![QQ截图20210207101506](https://user-images.githubusercontent.com/38741783/107134516-b8cfc100-692d-11eb-824a-f3322694e472.png)
![QQ截图20210207101517](https://user-images.githubusercontent.com/38741783/107134518-ba00ee00-692d-11eb-8163-b9fadcad8e17.png)

**Comment by serenibyss** [comment]
Will be closed by https://github.com/GregTechCE/GregTech/pull/1488

**Comment by Irgendwer01** [comment]
fixed in GTCE itself
