### ISSUE TITLE
No Route to MV from LV

### ISSUE THREAD

**Issue by MunkeeJuice** [GregTechCEu/gregicality-skyblock-edition#11]
I may be missing something but i have spent a few hours looking through JEI but i cannot see a way to craft 1x Copper Cable without having to use any MV machines and the fact you need 1x Copper Cable to craft MV Motors etc means you can't progress from LV to MV.

**Comment by huneau** [comment]
Hello, the path is not an easy one.
oil => sulfuric naphtha => naphtha
Nether => loking for niter ore => byproduct saltpeter 
naphtha + saltpeter => polycaprolactam  => solidified into ingot => bend it to plate => re-bend it to polycaprolactam foil 

Finally =>  polycaprolactam foil + copper wire = copper cable.

**Comment by huneau** [comment]
for help you can join us on discord => https://discord.gg/y5dkPtF 
Gregicality is not an easy mod

**Comment by MunkeeJuice** [comment]
Nice, will check it out, can't believe i missed it.
