### ISSUE TITLE
Hopping Bonsai Quest doesn't accept bonsais pots that you already placed once and mined again

### ISSUE THREAD

**Issue by joendter** [GregTechCEu/gregicality-skyblock-edition#14]
I placed my first bonsai pot and picked it up again to use it for the hopping bonsai quest but it wasn't accepted... Once I crafted a new one it didn't stack with the old one and was accepted by the quest

https://user-images.githubusercontent.com/71767955/108606537-e5b6b600-73ba-11eb-9827-aa456c47a9cd.mp4

**Comment by Irgendwer01** [comment]
Bonsai Trees got removed in 6.0
