### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by JackMeds** [GregTechCEu/gregicality-skyblock-edition#15]
https://paste.ubuntu.com/p/ZW8yNCjX9V/

**Comment by huneau** [comment]
what did you do to get this crash ?

**Comment by JackMeds** [comment]
> what did you do to get this crash ?

I did a lot of fluid synthesis, and then the AE system went to zero, and then crash

**Comment by JackMeds** [comment]
> what did you do to get this crash ?

At first I thought it was a problem with [mohist](https://github.com/Mohist-Community/Mohist), but when I use forgeserver back, it will still crash

**Comment by JackMeds** [comment]
> what did you do to get this crash ?

If I use creative energy cell from AE2, it won't go wrong.

**Comment by JackMeds** [comment]
> what did you do to get this crash ?

I think there will be a problem with the energy converter. How can I change it back to the default configuration? I'll try to see if it will crash

**Comment by JackMeds** [comment]
@huneau I tried to change ".minecraft\config\AppliedEnergistics2\AppliedEnergistics2.cfg in Line 368" to the default value, and there was no crash
-D:UsageMultiplier=100
+D:UsageMultiplier=1.0

**Comment by JackMeds** [comment]
> @huneau I tried to change ".minecraft\config\AppliedEnergistics2\AppliedEnergistics2.cfg in Line 368" to the default value, and there was no crash
> -D:UsageMultiplier=100
> +D:UsageMultiplier=1.0

and then I try 50
AE system will turn gray instantly, then recover, and then not crash
Large values(like 100) can cause a crash
Maybe we can modify the ratio of energy converter to achieve the original requirements

**Comment by JackMeds** [comment]
@huneau  I tried to remove foamfix, which seems to fix the problem and won't crash again

**Comment by Yefancy** [comment]
maybe my fault. are you using the dual interface from ae2fc? [issue](https://github.com/phantamanta44/ae2-fluid-crafting/issues/11)

**Comment by Yefancy** [comment]
It would be nice if you could send me the save, or the steps to reproduce this bug. This has been bothering me for a long time.

**Comment by JackMeds** [comment]
> It would be nice if you could send me the save, or the steps to reproduce this bug. This has been bothering me for a long time.

Sorry, I just saw it.
https://drive.google.com/file/d/1nzafd30ImcD8bK5N-O6yixfCqB52m_Da/view?usp=sharing

**Comment by Yefancy** [comment]
> > It would be nice if you could send me the save, or the steps to reproduce this bug. This has been bothering me for a long time.
> 
> Sorry, I just saw it.
> https://drive.google.com/file/d/1nzafd30ImcD8bK5N-O6yixfCqB52m_Da/view?usp=sharing


i don't have access to your Drive

**Comment by JackMeds** [comment]
> > > It would be nice if you could send me the save, or the steps to reproduce this bug. This has been bothering me for a long time.
> > 
> > 
> > Sorry, I just saw it.
> > https://drive.google.com/file/d/1nzafd30ImcD8bK5N-O6yixfCqB52m_Da/view?usp=sharing
> 
> i don't have access to your Drive

https://mega.nz/file/wVgzHCzB#_Z9t51xy_DoCFQjo8aCinLen1LzljhnSYyv2uzT864Y

**Comment by Yefancy** [comment]
> https://mega.nz/file/wVgzHCzB#_Z9t51xy_DoCFQjo8aCinLen1LzljhnSYyv2uzT864Y

really thanks for your help. but I can't seem to find a possible `save` or `world` from `greg.zip` (or i just not familiar with the Mohist directory). if that's all right, tell me the steps to reproduce it in a SP is also helpful.

![image](https://user-images.githubusercontent.com/18493855/109376832-23a76300-7902-11eb-81bd-2765fc69ae69.png)

**Comment by JackMeds** [comment]
> > https://mega.nz/file/wVgzHCzB#_Z9t51xy_DoCFQjo8aCinLen1LzljhnSYyv2uzT864Y
> 
> really thanks for your help. but I can't seem to find a possible `save` or `world` from `greg.zip` (or i just not familiar with the Mohist directory). if that's all right, tell me the steps to reproduce it in a SP is also helpful.
> 
> ![image](https://user-images.githubusercontent.com/18493855/109376832-23a76300-7902-11eb-81bd-2765fc69ae69.png)

Only need to use the ae2fc fluid synthesis to do a numerical value above 50K automation

**Comment by JackMeds** [comment]
@Yefancy  Have you found the problem? What else can I do for you?

**Comment by Yefancy** [comment]
Sry I still can't reproduce it.

**Comment by JackMeds** [comment]
> Sry I still can't reproduce it.

Players with this problem do use a lot of the dual interface from ae2fc. the latest discovery is that when the number of servers is small, this problem does not occur. When the number of players is large, the maximum time consumption of the server is only 34ms, which seems to have something to do with the memory

**Comment by Yefancy** [comment]
> Players with this problem do use a lot of the dual interface from ae2fc. the latest discovery is that when the number of servers is small, this problem does not occur. When the number of players is large, the maximum time consumption of the server is only 34ms, which seems to have something to do with the memory

i recompiled a version and tried to fix the bug. i hope you can help me to try it on your server (id appreciate it if you would). if this problem still there, i hope you can provide the log of the server to help me debug :)

[file](https://github.com/Yefancy/ae2-fluid-crafting/releases/download/test/ae2fc-test.jar)

**Comment by Yefancy** [comment]
@JackMeds a week has passed, and i wonder if this fix would work
