### ISSUE TITLE
Recipes about TurbineBlades

### ISSUE THREAD

**Issue by Moyurei** [GregTechCEu/gregicality-skyblock-edition#18]
Just now when I gotta make a rotor with turbine blades, I found two recipes with crafting table and forming press machine,  one using the normal kind of metal plates and another with dense plates. Is it designed so in this pack or maybe there is a mistakenly generated recipe?

**Comment by hjae78** [comment]
Will be fixed in next release

**Comment by Moyurei** [comment]
Thanks a lot :)
