### ISSUE TITLE
double plates have no recipes in the JEI

### ISSUE THREAD

**Issue by llx07** [GregTechCEu/gregicality-skyblock-edition#27]
double plates have no recipes in the JEI
so i can't craft fluid cell/turbine blade

**Comment by kenji11789** [comment]
I'm in trouble because I can't make a double plate .
Will it not be updated anymore?

**Comment by TechLord22** [comment]
Fixed in the latest github release.

**Comment by Rybalchenko-Ruslan** [comment]
Reject issue on 0.23.3
