### ISSUE TITLE
Invar Metal Casing crafting gives unusable Heat Proof Machine Casing

### ISSUE THREAD

**Issue by DarksteelMike** [GregTechCEu/gregicality-skyblock-edition#30]
Well.. Title. Their recipes are identical.

This is on the latest available Curseforge launcher version, I'm not behind on versions am I?

**Comment by WayneYam** [comment]
use forestry crafting table to choose which recipe you want to make for now

**Comment by TechLord22** [comment]
The Heat Proof casing is now the intended one for use in the latest Github release.
