### ISSUE TITLE
Robot arms recipes in assembler

### ISSUE THREAD

**Issue by Moyurei** [GregTechCEu/gregicality-skyblock-edition#31]
All kinds of robot arms have 2 recipes in the single block assembler within the same voltage, while default one asks for some more resources. As long as I prepare multiple items for mass production, the assembler always runs with the recipe which consumes more and upsets me.
Wish to be fixed soon ;)

**Comment by TechLord22** [comment]
This has been fixed in the latest Gregicality version and Github release.
