### ISSUE TITLE
Diamonds in Macerator recipe. Recipe for Aluminium?

### ISSUE THREAD

**Issue by VladParshin** [GregTechCEu/gregicality-skyblock-edition#48]
As per title, I've got version 6.3 of Gregicality Skyblock via Curseforge, started playing it and learning the pack.
However, are some of the steam recipes correct?
One that stood out was the steam Macerator requiring 2 diamonds. From what I can see, there is no way to produce diamonds from coal, nor can you obtain diamonds.
To get diamonds, it seems to require an Aluminium based Mesh for a sieve, but there is no way to transform Aluminium ore Chunks into ingots at the steam age.

**Comment by grskonieczny** [comment]
Yeah. It's blocking any progression. Flint would be good substitute.

**Comment by pigeonkevin** [comment]
But why can't flint be used as a tool for crushing bricks or as a substitute for diamonds in the formula of a steam grinder
