### ISSUE TITLE
Curseforge install fails on all release downloads

### ISSUE THREAD

**Issue by MgoMoar** [GregTechCEu/gregicality-skyblock-edition#8]
![Desktop Screenshot 2021 01 17 - 01 25 45 50](https://user-images.githubusercontent.com/68117986/104827859-01cab300-5863-11eb-8e6a-ed7036157bbd.png)
if you need any logs etc let me know, can reach me on curseforge username:mgomoarpr0  discord:[ṂĢסּ] Moar pr0👑¯\_(ツ)_/¯#3714
Best regards MGO

**Comment by Irgendwer01** [comment]
@MgoMoar Please Use GDLauncher as alternative for now https://gdevs.io

**Comment by Irgendwer01** [comment]
Fixed since a longer time
