### ISSUE TITLE
Hammers from Ex Nihilo aren't working

### ISSUE THREAD

**Issue by nohomosapiens** [GregTechCEu/gregicality-skyblock-edition#81]
Can't obtain crushed cobble, diorite, granite, etc. When I'm mining these blocks, a hammer just destroys them. However, if I use Chiseled blocks instead of Vanilla one, they will drop crushed stuff.

**Comment by joendter** [comment]
ex nihilo hammers have no mining level for some reason... yeah that's weird

**Comment by joendter** [comment]
fixed with 2.2.1
